name: CI-CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]  # Обновляем версию Node.js

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Обновляем до v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci  # Используем npm ci для быстрой установки зависимостей

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

  push_to_Docker_Hub:
    runs-on: ubuntu-latest
    needs: [build_test]
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2  # Обновляем до v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Обновляем до v2

      - name: Login to DockerHub
        uses: docker/login-action@v2  # Обновляем до v2
        with:
          username: ${{ secrets.REACTUSERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4  # Обновляем до v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          no-cache: true
          tags: ${{ secrets.REACTUSERNAME }}/sm-frontend:latest

      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.REACTUSERNAME }}/sm-frontend:latest
          run: |
            echo "running the docker image"

  push_to_vercel:
    runs-on: ubuntu-latest
    needs: [build_test]
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          vercel-args: "--prod"
